on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag with timestamp
        id: set_tag
        run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo $DOCKER_TOKEN | docker login --username cdapdev2020 --password-stdin
      
      - name: Build Docker image
        run: docker build -t cdapdev2020/djangoapiauthjwt:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: docker push cdapdev2020/djangoapiauthjwt:${{ env.IMAGE_TAG }}

